steps:
  - label: Example Test
    command: echo "Hello!"
  - label: test static on mac
    command: .buildkite/test-static-sanitized.sh
    agents:
      os: mac
  - label: test static on linux
    command: .buildkite/test-static-sanitized.sh
    agents:
      os: linux

