steps:
  - label: Example Test
    command: echo "Hello!"
  - label: ":mac: test static"
    command: .buildkite/test-static-sanitized.sh
    agents:
      os: mac
  - label: ":ubuntu: test static"
    command: .buildkite/test-static-sanitized.sh
    agents:
      os: linux
  - label: build emscripten on mac
    command: .buildkite/build-emscripten.sh
    agents:
      os: mac
