# There are two reasons we intentionally put everything we can on mac machine:
#  - our mac machine has 12 cores, while linux one has 4 cores.
#  - we use macs for development thus we want to make sure all scripts run there

steps:
  - label: ":cop: linters"
    command: .buildkite/linters.sh
    agents:
      os: mac
  - label: ":mac: test static"
    command: .buildkite/test-static-sanitized.sh
    artifact_paths: _out_/**/*
    agents:
      os: mac
  - label: ":ubuntu: test static"
    command: .buildkite/test-static-sanitized.sh
    artifact_paths: _out_/**/*
    agents:
      os: linux
  - label: ":yarn:"
    command: .buildkite/build-website.sh
    artifact_paths: _out_/**/*
    agents:
      os: mac
  - label: ":ruby: runtime"
    command: .buildkite/test-and-build-ruby-runtime.sh
    artifact_paths: _out_/**/*
    agents:
      os: mac
  - label: ":ruby: rbi-generation"
    command: .buildkite/test-and-build-rbi-generation.sh
    artifact_paths: _out_/**/*
    agents:
      os: mac
  - wait: ~
  - label: ":mac: :shipit:"
    artifact_paths: _out_/**/*
    command: .buildkite/release-static.sh
    agents:
      os: mac
  - label: ":javascript: build"
    command: .buildkite/build-emscripten.sh
    artifact_paths: _out_/**/*
    agents:
      os: mac
  - label: ":linux: :shipit:"
    artifact_paths: _out_/**/*
    command: .buildkite/release-static.sh
    agents:
      os: linux
