steps:
  - label: "linters"
    command: .buildkite/linters.sh
  - label: ":mac: test static"
    command: .buildkite/test-static-sanitized.sh
    artifact_paths: _out_/**/*
    agents:
      os: mac
  - label: ":ubuntu: test static"
    command: .buildkite/test-static-sanitized.sh
    artifact_paths: _out_/**/*
    agents:
      os: linux
  - label: ":javascript: build"
    command: .buildkite/build-emscripten.sh
    artifact_paths: _out_/**/*
    agents:
      os: mac
  - wait: ~
  - label: ":mac: :shipit:"
    artifact_paths: _out_/**/*
    command: .buildkite/release-static.sh
    agents:
      os: mac
  - label: ":linux: :shiptit:"
    artifact_paths: _out_/**/*
    command: .buildkite/release-static.sh
    agents:
      os: linux
