steps:
  - label: ":mac: test static"
    command: .buildkite/test-static-sanitized.sh
    agents:
      os: mac
  - label: ":ubuntu: test static"
    command: .buildkite/test-static-sanitized.sh
    agents:
      os: linux
  - label: ":javascript: build"
    command: .buildkite/build-emscripten.sh
    agents:
      os: mac
